---
# file: roles/developer/tasks/main.yml

- name: Install Dependencies
  apt:
    name: "{{ packages | flatten(levels=1) }}"
    state: "present"
    cache_valid_time: 3600
    install_recommends: false
  when:
    - ansible_distribution|lower == 'ubuntu'
  tags:
    - consul-inst-dependencies

- name: Inst - PIP Dependencies
  pip:
    name: "{{ item }}"
    executable: "pip3"
  loop: "{{ pip_packages }}"
  tags:
    - install-pip-deps

- name: Conf - Tmux
  become_user: "vagrant"
  get_url:
    url: "https://gist.githubusercontent.com/pmikus/bdb7a608f7abfcbc8854a6dcf2800716/raw/d685b7488d2cf9de4f67e196982fd72a724d90cd/.tmux.conf"
    dest: "/home/vagrant/.tmux.conf"
  tags:
    - conf-tmux

- name: Conf - Clone Tmux-tpm Repository
  become_user: "vagrant"
  git:
    repo: "https://github.com/tmux-plugins/tpm"
    dest: "/home/vagrant/.tmux/plugins/tpm"
    accept_hostkey: true
    force: true
  tags:
    - conf-tmux

#- name: Conf - Tmux Powerline
#  become_user: "vagrant"
#  git:
#    repo: "https://github.com/erikw/tmux-powerline.git"
#    dest: "/home/vagrant/.tmux/plugins/tmux-powerline"
#    accept_hostkey: True
#  tags:
#    - conf-tmux

- name: Conf - Vim
  become_user: "vagrant"
  get_url:
    url: "https://gist.githubusercontent.com/pmikus/cfc832cecb0464da3df311247dc174e3/raw/87f952cfa266b7f4e264a3e042ff5f301bf4d1e0/.vimrc"
    dest: "/home/vagrant/.vimrc"
  tags:
    - conf-vim

- name: Conf - VundleVim
  become_user: "vagrant"
  git:
    repo: "https://github.com/VundleVim/Vundle.vim.git"
    dest: "/home/vagrant/.vim/bundle/Vundle.vim"
    accept_hostkey: true
  tags:
    - conf-vim

#- name: Inst - Nerd-fonts Repository
#  become_user: "vagrant"
#  git:
#    repo: "https://github.com/ryanoasis/nerd-fonts"
#    dest: "/home/vagrant/nerd-fonts"
#    depth: 1
#    accept_hostkey: True
#  tags:
#    - install-fonts

#- name: Inst - Nerd-fonts
#  raw: "/home/vagrant/nerd-fonts/install.sh"
#  tags:
#    - install-fonts

#- name: Inst - Nerd-fonts update font-cache
#  raw: "fc-cache -vf"
#  tags:
#    - install-fonts
