---
# file: main.yaml

- hosts: vagrant
  connection: local
  become: true
  become_user: root
  gather_facts: false

  pre_tasks:
    - name: Gathering Facts
      gather_facts:
      tags:
        - always
    - name: Setting ansible distribution to Ubuntu
      set_fact: ansible_distribution="Ubuntu"

  roles:
    - role: pmikus.docker
      tags: docker
    - role: pmikus.nomad
      tags: nomad
    - role: pmikus.consul
      tags: consul
    - role: developer
      tags: developer

