---
# file: main.yaml

- hosts: vagrant
  connection: local
  become: true
  become_user: root
  gather_facts: false

  pre_tasks:
    - name: Gathering Facts
      gather_facts:
      tags:
        - always
  roles:
    - role: pmikus.docker
      tags: docker
    - role: pmikus.nomad
      tags: nomad
    - role: pmikus.consul
      tags: consul

  tasks:
    - name: Inst - package dependencies
      apt:
        name: "{{ item }}"
        state: "present"
        upgrade: true
        update_cache: true
        cache_valid_time: 3600
      loop:
        - "git"
      tags:
        - install-apt-update

    - name: Inst - pip dependencies
      pip:
        name: "{{ item }}"
      loop:
        - "docker-compose"
      tags:
        - install-pip-deps
