---
# file: requirements.yaml

roles:
  - name: "pmikus.docker"
    source: "https://galaxy.ansible.com"
  - name: "pmikus.nomad"
    source: "https://galaxy.ansible.com"
  - name: "pmikus.consul"
    source: "https://galaxy.ansible.com"
