---
# file: host_vars/127.0.0.1.yaml

# Nomad settings.
nomad_cli_cert_file: "{{ nomad_ssl_dir }}/nomad-cli.pem"
nomad_cli_key_file: "{{ nomad_ssl_dir }}/nomad-cli-key.pem"
nomad_certificates:
  - src: "{{ vault_nomad_ca_pem }}"
    dest: "{{ nomad_ca_file }}"
  - src: "{{ vault_nomad_server_pem }}"
    dest: "{{ nomad_cert_file }}"
  - src: "{{ vault_nomad_server_key_pem }}"
    dest: "{{ nomad_key_file }}"
  - src: "{{ vault_nomad_cli_pem }}"
    dest: "{{ nomad_cli_cert_file }}"
  - src: "{{ vault_nomad_cli_key_pem }}"
    dest: "{{ nomad_cli_key_file }}"
nomad_tls_enable: true
nomad_http: true
nomad_rpc: true
nomad_datacenter: "vagrant"
nomad_bootstrap_expect: 1
nomad_encrypt: "Y4T+5JGx1C3l2NFBBvkTWQ=="
nomad_node_name: "{{ ansible_hostname }}"
nomad_node_role: "both"
nomad_node_class: "compute"
nomad_options:
  driver.raw_exec.enable: false
  docker.privileged.enabled: false
  docker.volumes.enabled: true
  driver.whitelist: "docker"
nomad_service_mgr: "systemd"
nomad_volumes:
  - name: "volume-glacier1-1"
    path: "/glacier"
    read_only: false

# Consul settings.
consul_nomad_integration: true
consul_certificates:
  - src: "{{ vault_consul_agent_ca_pem }}"
    dest: "{{ consul_ca_file }}"
  - src: "{{ vault_consul_server_0_pem }}"
    dest: "{{ consul_cert_file }}"
  - src: "{{ vault_consul_server_0_key_pem }}"
    dest: "{{ consul_key_file }}"
consul_verify_incoming: true
consul_verify_outgoing: true
consul_vefify_server_hostname: false
consul_allow_tls: true
consul_datacenter: "vagrant"
consul_bootstrap_expect: 1
consul_encrypt: "Y4T+5JGx1C3l2NFBBvkTWQ=="
consul_node_name: "{{ ansible_hostname }}"
consul_node_role: "both"
consul_service_mgr: "systemd"

# Docker settings.
docker_daemon:
  dns: ["172.17.0.1"]
  dns-opts: []
  dns-search: ["{{ansible_hostname}}"]
docker_service_mgr: "systemd"
