---
# file: host_vars/127.0.0.1.yaml

# Nomad settings.
nomad_certificates:
  - src: "{{ file_nomad_ca_pem }}"
    dest: "{{ nomad_ca_file }}"
  - src: "{{ file_nomad_server_pem }}"
    dest: "{{ nomad_cert_file }}"
  - src: "{{ file_nomad_server_key_pem }}"
    dest: "{{ nomad_key_file }}"
nomad_datacenter: "vagrant"
nomad_encrypt: "Y4T+5JGx1C3l2NFBBvkTWQ=="
nomad_node_name: "{{ ansible_hostname }}"
nomad_node_role: "both"
nomad_node_class: "compute"
nomad_options:
  driver.raw_exec.enable: 1
  docker.privileged.enabled: true
  docker.volumes.enabled: true
  driver.whitelist: "docker"
nomad_service_mgr: "systemd"

# Consul settings.
consul_nomad_integration: true
consul_certificates:
  - src: "{{ file_consul_ca_pem }}"
    dest: "{{ consul_ca_file }}"
  - src: "{{ file_consul_server_0_pem }}"
    dest: "{{ consul_cert_file }}"
  - src: "{{ file_consul_server_0_key_pem }}"
    dest: "{{ consul_key_file }}"
consul_datacenter: "vagrant"
consul_encrypt: "Y4T+5JGx1C3l2NFBBvkTWQ=="
consul_node_name: "{{ hostname }}"
consul_node_role: "both"
consul_service_mgr: "systemd"

# Docker settings.
docker_daemon:
  dns: ["172.17.0.1"]
  dns-opts: []
  dns-search: ["{{ansible_hostname}}"]
docker_service_mgr: "systemd"
